#!/bin/bash

# Demo script for redis-cli-dashboard features

echo "🚀 redis-cli-dashboard - Advanced Redis/Valkey TUI Client Demo"
echo "================================================="
echo ""

echo "📋 Available Features:"
echo "  1. 🧭 Key Browser & Explorer"
echo "     • Pattern filtering (user:*, session:*)"
echo "     • Real-time search"
echo "     • TTL management"
echo "     • Value editing"
echo "     • JSON formatting"
echo ""
echo "  2. 📊 Performance Monitoring"
echo "     • Real-time metrics"
echo "     • Memory tracking"
echo "     • Connection monitoring"
echo "     • Cache analytics"
echo ""
echo "  3. 🧪 CLI with Advanced Features"
echo "     • Full Redis command support"
echo "     • Command history"
echo "     • Auto-completion"
echo "     • Scrollable output"
echo ""
echo "  4. 🔄 Advanced Data Visualization"
echo "     • All Redis data types supported"
echo "     • JSON formatting"
echo "     • Stream viewer"
echo "     • Binary-safe display"
echo ""
echo "  5. 🧑‍💼 Connection Management"
echo "     • Multiple connections"
echo "     • Database switching"
echo "     • Authentication support"
echo ""

echo "🎯 Quick Start:"
echo "  ./redis-cli-dashboard-enhanced                    # Main menu interface"
echo "  ./redis-cli-dashboard-enhanced -help             # Show full help"
echo ""

echo "⌨️  Navigation:"
echo "  ESC     : Return to main menu"
echo "  F1 / 1  : Key Browser mode"
echo "  F2 / 2  : Monitoring mode"
echo "  F3 / 3  : CLI mode"
echo "  F4 / 4  : Analytics mode"
echo "  F5 / 5  : Connections mode"
echo ""

echo "🔧 Key Browser Features:"
echo "  r       : Refresh keys"
echo "  d       : Delete selected key"
echo "  e       : Edit selected key"
echo "  t       : Set/modify TTL"
echo "  f       : Focus filter input"
echo "  s       : Focus search input"
echo ""

echo "📊 Supported Data Types:"
echo "  • String (with JSON formatting)"
echo "  • List (indexed display)"
echo "  • Set (sorted display)"
echo "  • Hash (field-value pairs)"
echo "  • Sorted Set (with scores)"
echo "  • Stream (basic support)"
echo ""

echo "🚀 To start the application:"
echo "  ./redis-cli-dashboard-enhanced"
echo ""
echo "Happy Redis management! 🎉"
